# Generated by Django 4.2.7 on 2024-07-18 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='animes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atitle', models.CharField(max_length=50)),
                ('adescription', models.TextField(max_length=300)),
                ('avideo', models.FileField(upload_to='video')),
                ('aimage', models.ImageField(upload_to='img/thumbnail')),
                ('acategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v_core.category')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
            },
        ),
    ]
